CREATE TABLE discount
(

    discount_id   INTEGER           NOT NULL,

    description   VARCHAR2(30 CHAR),

    discount_type VARCHAR2(15 CHAR) NOT NULL,

    percent_value INTEGER,

    amount        INTEGER,

    status        VARCHAR2(15 CHAR) NOT NULL,

    start_on      TIMESTAMP         NOT NULL,

    ends_on       TIMESTAMP         NOT NULL,

    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    modified_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

ALTER TABLE discount
    ADD CONSTRAINT discount_pk PRIMARY KEY (discount_id);


CREATE TABLE "Order"
(
    order_id       INTEGER NOT NULL,

    status         VARCHAR2(15 CHAR),

    total_amount   NUMBER(10, 2),

    created_at     TIMESTAMP,

    modified_at    TIMESTAMP,

    user_id        VARCHAR2(20 CHAR),

    payment_det_id INTEGER
);


CREATE UNIQUE INDEX order__idx ON
    "Order" (
             payment_det_id
             ASC);



ALTER TABLE "Order"
    ADD CONSTRAINT order_pk PRIMARY KEY (order_id);



CREATE TABLE orderproduct
(

    order_product_id INTEGER   NOT NULL,

    quantity         INTEGER   NOT NULL,

    created_at       TIMESTAMP NOT NULL,

    updated_at       TIMESTAMP NOT NULL,

    order_id         INTEGER   NOT NULL,

    product_id       INTEGER

);

ALTER TABLE orderproduct
    ADD CONSTRAINT orderproduct_pk PRIMARY KEY (order_product_id);



CREATE TABLE payment
(

    payment_id  INTEGER           NOT NULL,

    pay_type    VARCHAR2(15 CHAR) NOT NULL,

    account_num VARCHAR2(25 CHAR),

    card_number VARCHAR2(19 CHAR),

    cc_exp_date VARCHAR2(14 CHAR),

    cc_code     VARCHAR2(4 CHAR),

    created_at  TIMESTAMP         NOT NULL,

    modified_at TIMESTAMP         NOT NULL,

    user_id     VARCHAR2(20 CHAR)

);

ALTER TABLE payment
    ADD CONSTRAINT payment_pk PRIMARY KEY (payment_id);



CREATE TABLE paymentdetails
(

    payment_det_id INTEGER           NOT NULL,

    status         VARCHAR2(15 CHAR) NOT NULL,

    amount         INTEGER           NOT NULL,

    created_at     TIMESTAMP         NOT NULL,

    modified_at    TIMESTAMP         NOT NULL,

    order_id       INTEGER           NOT NULL,

    payment_id     INTEGER

);



CREATE UNIQUE INDEX paymentdetails__idx ON
    paymentdetails (
                    order_id
                    ASC);



ALTER TABLE paymentdetails
    ADD CONSTRAINT paymentdetails_pk PRIMARY KEY (payment_det_id);



CREATE TABLE product
(

    product_id  INTEGER           NOT NULL,

    price       INTEGER           NOT NULL,

    description VARCHAR2(50 CHAR),

    category    VARCHAR2(15 CHAR) NOT NULL,

    created_at  TIMESTAMP         NOT NULL,

    uppdated_at TIMESTAMP         NOT NULL

);



ALTER TABLE product
    ADD CONSTRAINT product_pk PRIMARY KEY (product_id);



CREATE TABLE orderproduct_discount
(

    orderproduct_id INTEGER NOT NULL,

    discount_id     INTEGER NOT NULL

);


ALTER TABLE orderproduct_discount

    ADD CONSTRAINT orderproduct_discount_pk PRIMARY KEY (orderproduct_id,
                                                         discount_id);



CREATE TABLE "User"
(

    user_id     VARCHAR2(20 CHAR) NOT NULL,

    passwd      CHAR(60 CHAR)     NOT NULL,

    created_at  TIMESTAMP         NOT NULL,

    modified_at TIMESTAMP         NOT NULL

);


ALTER TABLE "User"
    ADD CONSTRAINT user_pk PRIMARY KEY (user_id);



ALTER TABLE "Order"

    ADD CONSTRAINT order_paymentdetails_fk FOREIGN KEY (payment_det_id)
        REFERENCES paymentdetails (payment_det_id);


ALTER TABLE "Order"

    ADD CONSTRAINT order_user_fk FOREIGN KEY (user_id)
        REFERENCES "User" (user_id);


ALTER TABLE orderproduct

    ADD CONSTRAINT orderproduct_order_fk FOREIGN KEY (order_id)
        REFERENCES "Order" (order_id);


ALTER TABLE orderproduct

    ADD CONSTRAINT orderproduct_product_fk FOREIGN KEY (product_id)
        REFERENCES product (product_id);


ALTER TABLE payment

    ADD CONSTRAINT payment_user_fk FOREIGN KEY (user_id)
        REFERENCES "User" (user_id);


ALTER TABLE paymentdetails

    ADD CONSTRAINT paymentdetails_order_fk FOREIGN KEY (order_id)
        REFERENCES "Order" (order_id);


ALTER TABLE paymentdetails

    ADD CONSTRAINT paymentdetails_payment_fk FOREIGN KEY (payment_id)
        REFERENCES payment (payment_id);


ALTER TABLE orderproduct_discount

    ADD CONSTRAINT orderproduct_discount_d_fk FOREIGN KEY (discount_id)
        REFERENCES discount (discount_id);

ALTER TABLE orderproduct_discount

    ADD CONSTRAINT orderproduct_discount_op_fk FOREIGN KEY (orderproduct_id)
        REFERENCES ORDERPRODUCT (order_product_id);

CREATE TABLE ORDER_LOG
(
    log_id   NUMBER            generated by default as identity,
    order_id NUMBER            NOT NULL,
    status   VARCHAR2(15 CHAR) NOT NULL,
    msg      VARCHAR2(150)     NOT NULL,
    reported TIMESTAMP         NOT NULL
);

ALTER TABLE ORDER_LOG
    ADD CONSTRAINT pk_log_id PRIMARY KEY (log_id);